package com.nankai.app.domain;

// Generated 2017-7-20 17:13:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer departmentId;//部门Id
	private Organization organization;//所属组织
	private Member member;//部门老大
	private String departmentName;//部门名
	private Set members = new HashSet(0);//部门下辖组织所有成员
	private Set registersForRegisterIntention2 = new HashSet(0);//意向2为部门下辖组织的注册者
	private Set registersForRegisterIntention1 = new HashSet(0);//意向1为部门下辖组织的注册者

	public Department() {
	}

	public Department(Organization organization, Member member,
			String departmentName) {
		this.organization = organization;
		this.member = member;
		this.departmentName = departmentName;
	}

	public Department(Organization organization, Member member,
			String departmentName, Set members,
			Set registersForRegisterIntention2,
			Set registersForRegisterIntention1) {
		this.organization = organization;
		this.member = member;
		this.departmentName = departmentName;
		this.members = members;
		this.registersForRegisterIntention2 = registersForRegisterIntention2;
		this.registersForRegisterIntention1 = registersForRegisterIntention1;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public Set getMembers() {
		return this.members;
	}

	public void setMembers(Set members) {
		this.members = members;
	}

	public Set getRegistersForRegisterIntention2() {
		return this.registersForRegisterIntention2;
	}

	public void setRegistersForRegisterIntention2(
			Set registersForRegisterIntention2) {
		this.registersForRegisterIntention2 = registersForRegisterIntention2;
	}

	public Set getRegistersForRegisterIntention1() {
		return this.registersForRegisterIntention1;
	}

	public void setRegistersForRegisterIntention1(
			Set registersForRegisterIntention1) {
		this.registersForRegisterIntention1 = registersForRegisterIntention1;
	}

}
