package com.nankai.app.domain;

// Generated 2017-7-20 17:13:46 by Hibernate Tools 3.4.0.CR1

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

	private Integer materialId;
	private Organization organization;
	private String materialName;
	private int materialAmount;
	private String materialRemarks;

	public String getMaterialRemarks() {
		return materialRemarks;
	}

	public void setMaterialRemarks(String materialRemarks) {
		this.materialRemarks = materialRemarks;
	}

	public Material() {
	}

	public Material(Organization organization, String materialName,
			int materialAmount) {
		this.organization = organization;
		this.materialName = materialName;
		this.materialAmount = materialAmount;
	}

	public Integer getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public String getMaterialName() {
		return this.materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	public int getMaterialAmount() {
		return this.materialAmount;
	}

	public void setMaterialAmount(int materialAmount) {
		this.materialAmount = materialAmount;
	}

}
