package com.nankai.app.domain;

// Generated 2017-7-20 17:13:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private Integer memberId;
	private Department department;
	private String memberName;
	private String memberMajor;
	private String memberHometown;
	private String memberBirthday;
	private String memberGender;
	private String memberPassword;
	private String memberPosition;
	private String memberPhone;
	private String memberPicture;
	
	public String getMemberPicture() {
		return memberPicture;
	}

	public void setMemberPicture(String memberPicture) {
		this.memberPicture = memberPicture;
	}

	private Set departments = new HashSet(0);
	public String getOldmemberPassword() {
		return oldmemberPassword;
	}

	public void setOldmemberPassword(String oldmemberPassword) {
		this.oldmemberPassword = oldmemberPassword;
	}

	public String getNewmemberPassword() {
		return newmemberPassword;
	}

	public void setNewmemberPassword(String newmemberPassword) {
		this.newmemberPassword = newmemberPassword;
	}

	public String getRememberPassword() {
		return rememberPassword;
	}

	public void setRememberPassword(String rememberPassword) {
		this.rememberPassword = rememberPassword;
	}

	private String oldmemberPassword;
	private String newmemberPassword;
	private String rememberPassword;
	

	public Member() {
	}

	public Member(Department department, String memberName, String memberMajor,
			String memberHometown, String memberBirthday, String memberGender,
			String memberPassword, String memberPosition, String memberPhone,String memberPicture) {
		this.department = department;
		this.memberName = memberName;
		this.memberMajor = memberMajor;
		this.memberHometown = memberHometown;
		this.memberBirthday = memberBirthday;
		this.memberGender = memberGender;
		this.memberPassword = memberPassword;
		this.memberPosition = memberPosition;
		this.memberPhone = memberPhone;
		this.memberPicture=memberPicture;
	}

	public Member(Department department, String memberName, String memberMajor,
			String memberHometown, String memberBirthday, String memberGender,
			String memberPassword, String memberPosition, String memberPhone,String memberPicture,
			Set departments) {
		this.department = department;
		this.memberName = memberName;
		this.memberMajor = memberMajor;
		this.memberHometown = memberHometown;
		this.memberBirthday = memberBirthday;
		this.memberGender = memberGender;
		this.memberPassword = memberPassword;
		this.memberPosition = memberPosition;
		this.memberPhone = memberPhone;
		this.departments = departments;
		this.memberPicture=memberPicture;
	}

	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	public String getMemberMajor() {
		return this.memberMajor;
	}

	public void setMemberMajor(String memberMajor) {
		this.memberMajor = memberMajor;
	}

	public String getMemberHometown() {
		return this.memberHometown;
	}

	public void setMemberHometown(String memberHometown) {
		this.memberHometown = memberHometown;
	}

	public String getMemberBirthday() {
		return this.memberBirthday;
	}

	public void setMemberBirthday(String memberBirthday) {
		this.memberBirthday = memberBirthday;
	}

	public String getMemberGender() {
		return this.memberGender;
	}

	public void setMemberGender(String memberGender) {
		this.memberGender = memberGender;
	}

	public String getMemberPassword() {
		return this.memberPassword;
	}

	public void setMemberPassword(String memberPassword) {
		this.memberPassword = memberPassword;
	}

	public String getMemberPosition() {
		return this.memberPosition;
	}

	public void setMemberPosition(String memberPosition) {
		this.memberPosition = memberPosition;
	}

	public String getMemberPhone() {
		return this.memberPhone;
	}

	public void setMemberPhone(String memberPhone) {
		this.memberPhone = memberPhone;
	}

	public Set getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set departments) {
		this.departments = departments;
	}

}
