package com.nankai.app.domain;

// Generated 2017-7-20 17:13:46 by Hibernate Tools 3.4.0.CR1

/**
 * Register generated by hbm2java
 */
public class Register implements java.io.Serializable {

	private Integer registerId;
	private Department departmentByRegisterIntention1;
	private Department departmentByRegisterIntention2;
	private String registerName;
	private String registerPassword;
	private String registerIntroduction;
	private String registerMajor;
	private String registerHometown;
	private String registerBirthday;
	private String registerGender;
	private String registerPhone;
	private String registerPicture;
	private Integer registerStatus;
	private String registerAdjust;
	private String registerDate;
	public Register() {
	}

	public Register(Department departmentByRegisterIntention1,
			Department departmentByRegisterIntention2, String registerName,String registerPassword,
			String registerIntroduction, String registerMajor,
			String registerHometown, String registerBirthday,
			String registerGender, String registerPhone,
			String registerPicture, Integer registerStatus,
			String registerAdjust,String registerDate) {
		this.departmentByRegisterIntention1 = departmentByRegisterIntention1;
		this.departmentByRegisterIntention2 = departmentByRegisterIntention2;
		this.registerName = registerName;
		this.registerPassword=registerPassword;
		this.registerIntroduction = registerIntroduction;
		this.registerMajor = registerMajor;
		this.registerHometown = registerHometown;
		this.registerBirthday = registerBirthday;
		this.registerGender = registerGender;
		this.registerPhone = registerPhone;
		this.registerPicture = registerPicture;
		this.registerStatus = registerStatus;
		this.registerAdjust = registerAdjust;
		this.registerDate=registerDate;
	}
	
	public String getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(String registerDate) {
		this.registerDate = registerDate;
	}

	public String getRegisterPassword() {
		return registerPassword;
	}

	public void setRegisterPassword(String registerPassword) {
		this.registerPassword = registerPassword;
	}

	public Integer getRegisterId() {
		return this.registerId;
	}

	public void setRegisterId(Integer registerId) {
		this.registerId = registerId;
	}

	public Department getDepartmentByRegisterIntention1() {
		return this.departmentByRegisterIntention1;
	}

	public void setDepartmentByRegisterIntention1(
			Department departmentByRegisterIntention1) {
		this.departmentByRegisterIntention1 = departmentByRegisterIntention1;
	}

	public Department getDepartmentByRegisterIntention2() {
		return this.departmentByRegisterIntention2;
	}

	public void setDepartmentByRegisterIntention2(
			Department departmentByRegisterIntention2) {
		this.departmentByRegisterIntention2 = departmentByRegisterIntention2;
	}

	public String getRegisterName() {
		return this.registerName;
	}

	public void setRegisterName(String registerName) {
		this.registerName = registerName;
	}

	public String getRegisterIntroduction() {
		return this.registerIntroduction;
	}

	public void setRegisterIntroduction(String registerIntroduction) {
		this.registerIntroduction = registerIntroduction;
	}

	public String getRegisterMajor() {
		return this.registerMajor;
	}

	public void setRegisterMajor(String registerMajor) {
		this.registerMajor = registerMajor;
	}

	public String getRegisterHometown() {
		return this.registerHometown;
	}

	public void setRegisterHometown(String registerHometown) {
		this.registerHometown = registerHometown;
	}

	public String getRegisterBirthday() {
		return this.registerBirthday;
	}

	public void setRegisterBirthday(String registerBirthday) {
		this.registerBirthday = registerBirthday;
	}

	public String getRegisterGender() {
		return this.registerGender;
	}

	public void setRegisterGender(String registerGender) {
		this.registerGender = registerGender;
	}

	public String getRegisterPhone() {
		return this.registerPhone;
	}

	public void setRegisterPhone(String registerPhone) {
		this.registerPhone = registerPhone;
	}

	public String getRegisterPicture() {
		return this.registerPicture;
	}

	public void setRegisterPicture(String registerPicture) {
		this.registerPicture = registerPicture;
	}

	public Integer getRegisterStatus() {
		return this.registerStatus;
	}

	public void setRegisterStatus(Integer registerStatus) {
		this.registerStatus = registerStatus;
	}

	public String getRegisterAdjust() {
		return this.registerAdjust;
	}

	public void setRegisterAdjust(String registerAdjust) {
		this.registerAdjust = registerAdjust;
	}

}
